# Golang CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    working_directory: /go/src/github.com/dillonhafer/budgetal-go
    steps:
      - checkout
      - run:
          name: Installing psql
          command: sudo apt-get install postgresql-client

      - run: mkdir -p /go/src/github.com/gobuffalo
      - run: git clone https://github.com/gobuffalo/buffalo /go/src/github.com/gobuffalo/buffalo
      - run: cd /go/src/github.com/gobuffalo/buffalo && git checkout tags/v0.10.1
      - run: go get github.com/gobuffalo/buffalo/...
      - run: go install github.com/gobuffalo/buffalo/buffalo
      - run: go get -t -d ./...
      - run: cd backend && buffalo db create -e test
      - run: cd backend && buffalo db m -e test
      - run: cd backend && buffalo test
